# =================================================================
#
# Authors: doublebyte1 <jo@byteroad.net>>
#          pascalike <ant@byteroad.net>
#
# Copyright (c) 2022 doublebyte
# Copyright (c) 2019 pascalike
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

services:

  apache-httpd:
    image: httpd:2.4
    depends_on:
      - pygeoapi
    volumes:
      - ./apache-httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
      - "443:443"
    command: sh -c "/usr/local/apache2/bin/htpasswd -b -c /usr/local/apache2/.htpasswd $FROST_USER $FROST_PASSWORD && httpd-foreground"
    container_name: apache-httpd
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi_es
    entrypoint:
      - /es-entrypoint.sh
    expose:
      - "80"
    environment:
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    env_file:
      - .env     # path to your .env file
    volumes:
      - ./pygeoapi/docker.config.local.yml:/pygeoapi/local.config.yml
      - ./pygeoapi/es-entrypoint.sh:/es-entrypoint.sh
      - ./pygeoapi/wait-for-elasticsearch.sh:/wait-for-elasticsearch.sh
      - ./ES/data:/data
    links:
      - elastic_search
    depends_on:
      - elastic_search
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G

  elastic_search:
    build: ./ES
    container_name: elastic
    privileged: true
    environment:
       - "discovery.type=single-node"
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
       memlock:
         soft: -1
         hard: -1
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 4G

  sisyphus:
    image: ghcr.io/emotional-cities/sisyphusapi:main
    container_name: sisyphus
    environment:
      ENV_STATE: "dev"
      DEV_ELASTIC_HOST: "elastic"
      DEV_ELASTIC_PORT: "9200"
      DEV_ELASTIC_INDEX: "ec_catalog"
      DEV_LOG_PATH: "./logs"
      DEV_LOG_FILENAME: "sisyphus.log"
      DEV_LOG_LEVEL: "DEBUG"
      DEV_LOG_ROTATION: "500 MB"
      DEV_LOG_RETENTION: "10 days"
      DEV_LOG_FORMAT: "{time} {level} {message}"
    expose:
      - 80
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G

volumes:
  elastic_search_data: {}

#NOTE: Host requires changes in configuration to run ES
#sudo sysctl -w vm.max_map_count=262144
